name: "🍘 Deploy: stacks"
run-name: "${{ ((inputs.dry-run || 'true') != 'true') && ((inputs.destroy == 'true') && 'Destroy' || 'Deploy') || 'Plan' }} ${{ (inputs.environment == '') && 'dev.rp.az.gebit.cloud' || inputs.environment }} ${{ github.ref }} [${{inputs.stack-filter || '🍘'}}]"

on:
  # pull_request:
  # branches:
  #   - feature/*
  workflow_dispatch:
    inputs:
      # TODO: replace with deploy-config stack props
      dry-run:
        description: "Run only dry-run"
        required: true
        type: choice
        options:
          - "true"
          - "false"
      stack-filter:
        description: "comma separated list of stack ids: e.g.: vnet-dns,managed-identities"
        required: false
        default: ""
      environment:
        description: "Deployment github environment"
        required: true
        default: "dev.rp.az.gebit.cloud"
      # destroy:
      #   description: "Destroy"
      #   required: false
      #   type: choice
      #   default: "false"
      #   options:
      #     - "true"
      #     - "false"
      deploy-config:
        description: "Deploy-Config filename (wihtout .yaml) in configs folder"
        required: false
        type: string
        default: ""

concurrency:
  group: ${{ inputs.dry-run == 'true' && github.sha || inputs.environment }}
  cancel-in-progress: false

jobs:
  setup:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-setup-ci.yml@mainv2
    name: "Setup CI/CD"
    secrets: inherit
    with:
      project: "rpoa"
      stack_filter: "${{ inputs.stack-filter || '' }}"
      environment: "${{ inputs.environment || 'dev.rp.az.gebit.cloud' }}"
      dry-run: "${{ inputs.dry-run || 'true' }}"
      runs-on: ${{ vars.RUNNER || 'ubuntu-22.04' }}
      release_config_filepath: "configs/${{ inputs.deploy-config || 'deploy-config-default' }}.yaml"

  l0:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    needs: [setup]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[0].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[0] }}
    with:
      default-location: ${{ needs.setup.outputs.default-location }}
      env: ${{ needs.setup.outputs.env }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l1:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[1][0] != null
    needs: [setup, l0]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[1].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[1] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l2:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[2][0] != null
    needs: [setup, l0, l1]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[2].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[2] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l3:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[3][0] != null
    needs: [setup, l0, l1, l2]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[3].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[3] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l4:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[4][0] != null
    needs: [setup, l0, l1, l2, l3]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[4].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[4] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l5:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[5][0] != null
    needs: [setup, l0, l1, l2, l3, l4]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[5].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[5] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l6:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[6][0] != null
    needs: [setup, l0, l1, l2, l3, l4, l5]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[6].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[6] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l7:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[7][0] != null
    needs: [setup, l0, l1, l2, l3, l4, l5, l6]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[7].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[7] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l8:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[8][0] != null
    needs: [setup, l0, l1, l2, l3, l4, l5, l6, l7]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[8].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[8] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l9:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[9][0] != null
    needs: [setup, l0, l1, l2, l3, l4, l5, l6, l7, l8]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[9].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[9] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit

  l10:
    uses: GEBITSolutions/itis-shared-code/.github/workflows/a-wf-deploy-stack.yml@mainv2
    if: fromJson(needs.setup.outputs.ci-config)[10][0] != null
    needs: [setup, l0, l1, l2, l3, l4, l5, l6, l7, l8, l9]
    name: ${{ join(fromJson(needs.setup.outputs.ci-config)[10].*.name,',') || 'No Jobs' }}
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.setup.outputs.ci-config)[10] }}
    with:
      env: ${{ needs.setup.outputs.env }}
      default-location: ${{ needs.setup.outputs.default-location }}
      data: "${{ toJson(matrix.data) }}"
      external-repos: "${{ needs.setup.outputs.external-repos }}"
    secrets: inherit
